C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/4,3/
      DATA (SPROP(I,-1,1),I=1,2)/21,21/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/5,-1/
      DATA (SPROP(I,-2,1),I=1,2)/5,-5/
      DATA TPRID(-2,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/5,3/
      DATA (SPROP(I,-1,2),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/4,-1/
      DATA (SPROP(I,-2,2),I=1,2)/5,-5/
      DATA TPRID(-2,2)/0/
C     Diagram 3
      DATA MAPCONFIG(3)/3/
      DATA (IFOREST(I,-1,3),I=1,2)/5,3/
      DATA (SPROP(I,-1,3),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,3)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/4,-1/
      DATA (SPROP(I,-2,3),I=1,2)/5,-5/
      DATA TPRID(-2,3)/0/
C     Diagram 4
      DATA MAPCONFIG(4)/4/
      DATA (IFOREST(I,-1,4),I=1,2)/5,4/
      DATA (SPROP(I,-1,4),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,4)/0/
      DATA (IFOREST(I,-2,4),I=1,2)/-1,3/
      DATA (SPROP(I,-2,4),I=1,2)/5,-5/
      DATA TPRID(-2,4)/0/
C     Diagram 5
      DATA MAPCONFIG(5)/5/
      DATA (IFOREST(I,-1,5),I=1,2)/5,4/
      DATA (SPROP(I,-1,5),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,5)/0/
      DATA (IFOREST(I,-2,5),I=1,2)/-1,3/
      DATA (SPROP(I,-2,5),I=1,2)/5,-5/
      DATA TPRID(-2,5)/0/
C     Diagram 6
      DATA MAPCONFIG(6)/6/
      DATA (IFOREST(I,-1,6),I=1,2)/1,3/
      DATA TPRID(-1,6)/1000021/
      DATA (SPROP(I,-1,6),I=1,2)/0,0/
      DATA (IFOREST(I,-2,6),I=1,2)/-1,5/
      DATA TPRID(-2,6)/1000005/
      DATA (SPROP(I,-2,6),I=1,2)/0,0/
      DATA (IFOREST(I,-3,6),I=1,2)/-2,4/
C     Diagram 7
      DATA MAPCONFIG(7)/7/
      DATA (IFOREST(I,-1,7),I=1,2)/1,3/
      DATA TPRID(-1,7)/1000021/
      DATA (SPROP(I,-1,7),I=1,2)/0,0/
      DATA (IFOREST(I,-2,7),I=1,2)/-1,5/
      DATA TPRID(-2,7)/2000005/
      DATA (SPROP(I,-2,7),I=1,2)/0,0/
      DATA (IFOREST(I,-3,7),I=1,2)/-2,4/
C     Diagram 8
      DATA MAPCONFIG(8)/8/
      DATA (IFOREST(I,-1,8),I=1,2)/1,3/
      DATA TPRID(-1,8)/1000021/
      DATA (SPROP(I,-1,8),I=1,2)/0,0/
      DATA (IFOREST(I,-2,8),I=1,2)/-1,4/
      DATA TPRID(-2,8)/21/
      DATA (SPROP(I,-2,8),I=1,2)/0,0/
      DATA (IFOREST(I,-3,8),I=1,2)/-2,5/
C     Diagram 9
      DATA MAPCONFIG(9)/9/
      DATA (IFOREST(I,-1,9),I=1,2)/5,4/
      DATA (SPROP(I,-1,9),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,9)/0/
      DATA (IFOREST(I,-2,9),I=1,2)/1,3/
      DATA TPRID(-2,9)/1000021/
      DATA (SPROP(I,-2,9),I=1,2)/0,0/
      DATA (IFOREST(I,-3,9),I=1,2)/-2,-1/
C     Diagram 10
      DATA MAPCONFIG(10)/10/
      DATA (IFOREST(I,-1,10),I=1,2)/5,4/
      DATA (SPROP(I,-1,10),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,10)/0/
      DATA (IFOREST(I,-2,10),I=1,2)/1,3/
      DATA TPRID(-2,10)/1000021/
      DATA (SPROP(I,-2,10),I=1,2)/0,0/
      DATA (IFOREST(I,-3,10),I=1,2)/-2,-1/
C     Diagram 11
      DATA MAPCONFIG(11)/11/
      DATA (IFOREST(I,-1,11),I=1,2)/1,4/
      DATA TPRID(-1,11)/1000021/
      DATA (SPROP(I,-1,11),I=1,2)/0,0/
      DATA (IFOREST(I,-2,11),I=1,2)/-1,5/
      DATA TPRID(-2,11)/1000005/
      DATA (SPROP(I,-2,11),I=1,2)/0,0/
      DATA (IFOREST(I,-3,11),I=1,2)/-2,3/
C     Diagram 12
      DATA MAPCONFIG(12)/12/
      DATA (IFOREST(I,-1,12),I=1,2)/1,4/
      DATA TPRID(-1,12)/1000021/
      DATA (SPROP(I,-1,12),I=1,2)/0,0/
      DATA (IFOREST(I,-2,12),I=1,2)/-1,5/
      DATA TPRID(-2,12)/2000005/
      DATA (SPROP(I,-2,12),I=1,2)/0,0/
      DATA (IFOREST(I,-3,12),I=1,2)/-2,3/
C     Diagram 13
      DATA MAPCONFIG(13)/13/
      DATA (IFOREST(I,-1,13),I=1,2)/1,4/
      DATA TPRID(-1,13)/1000021/
      DATA (SPROP(I,-1,13),I=1,2)/0,0/
      DATA (IFOREST(I,-2,13),I=1,2)/-1,3/
      DATA TPRID(-2,13)/21/
      DATA (SPROP(I,-2,13),I=1,2)/0,0/
      DATA (IFOREST(I,-3,13),I=1,2)/-2,5/
C     Diagram 14
      DATA MAPCONFIG(14)/14/
      DATA (IFOREST(I,-1,14),I=1,2)/5,3/
      DATA (SPROP(I,-1,14),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,14)/0/
      DATA (IFOREST(I,-2,14),I=1,2)/1,4/
      DATA TPRID(-2,14)/1000021/
      DATA (SPROP(I,-2,14),I=1,2)/0,0/
      DATA (IFOREST(I,-3,14),I=1,2)/-2,-1/
C     Diagram 15
      DATA MAPCONFIG(15)/15/
      DATA (IFOREST(I,-1,15),I=1,2)/5,3/
      DATA (SPROP(I,-1,15),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,15)/0/
      DATA (IFOREST(I,-2,15),I=1,2)/1,4/
      DATA TPRID(-2,15)/1000021/
      DATA (SPROP(I,-2,15),I=1,2)/0,0/
      DATA (IFOREST(I,-3,15),I=1,2)/-2,-1/
C     Diagram 16
      DATA MAPCONFIG(16)/16/
      DATA (IFOREST(I,-1,16),I=1,2)/1,5/
      DATA TPRID(-1,16)/5/
      DATA (SPROP(I,-1,16),I=1,2)/0,0/
      DATA (IFOREST(I,-2,16),I=1,2)/-1,4/
      DATA TPRID(-2,16)/1000005/
      DATA (SPROP(I,-2,16),I=1,2)/0,0/
      DATA (IFOREST(I,-3,16),I=1,2)/-2,3/
C     Diagram 17
      DATA MAPCONFIG(17)/17/
      DATA (IFOREST(I,-1,17),I=1,2)/1,5/
      DATA TPRID(-1,17)/5/
      DATA (SPROP(I,-1,17),I=1,2)/0,0/
      DATA (IFOREST(I,-2,17),I=1,2)/-1,4/
      DATA TPRID(-2,17)/2000005/
      DATA (SPROP(I,-2,17),I=1,2)/0,0/
      DATA (IFOREST(I,-3,17),I=1,2)/-2,3/
C     Diagram 18
      DATA MAPCONFIG(18)/18/
      DATA (IFOREST(I,-1,18),I=1,2)/1,5/
      DATA TPRID(-1,18)/5/
      DATA (SPROP(I,-1,18),I=1,2)/0,0/
      DATA (IFOREST(I,-2,18),I=1,2)/-1,3/
      DATA TPRID(-2,18)/1000005/
      DATA (SPROP(I,-2,18),I=1,2)/0,0/
      DATA (IFOREST(I,-3,18),I=1,2)/-2,4/
C     Diagram 19
      DATA MAPCONFIG(19)/19/
      DATA (IFOREST(I,-1,19),I=1,2)/1,5/
      DATA TPRID(-1,19)/5/
      DATA (SPROP(I,-1,19),I=1,2)/0,0/
      DATA (IFOREST(I,-2,19),I=1,2)/-1,3/
      DATA TPRID(-2,19)/2000005/
      DATA (SPROP(I,-2,19),I=1,2)/0,0/
      DATA (IFOREST(I,-3,19),I=1,2)/-2,4/
C     Diagram 20
      DATA MAPCONFIG(20)/20/
      DATA (IFOREST(I,-1,20),I=1,2)/4,3/
      DATA (SPROP(I,-1,20),I=1,2)/21,21/
      DATA TPRID(-1,20)/0/
      DATA (IFOREST(I,-2,20),I=1,2)/1,5/
      DATA TPRID(-2,20)/5/
      DATA (SPROP(I,-2,20),I=1,2)/0,0/
      DATA (IFOREST(I,-3,20),I=1,2)/-2,-1/
C     Diagram 21
      DATA MAPCONFIG(21)/21/
      DATA (IFOREST(I,-1,21),I=1,2)/5,4/
      DATA (SPROP(I,-1,21),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,21)/0/
      DATA (IFOREST(I,-2,21),I=1,2)/1,-1/
      DATA TPRID(-2,21)/1000005/
      DATA (SPROP(I,-2,21),I=1,2)/0,0/
      DATA (IFOREST(I,-3,21),I=1,2)/-2,3/
C     Diagram 22
      DATA MAPCONFIG(22)/22/
      DATA (IFOREST(I,-1,22),I=1,2)/5,4/
      DATA (SPROP(I,-1,22),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,22)/0/
      DATA (IFOREST(I,-2,22),I=1,2)/1,-1/
      DATA TPRID(-2,22)/1000005/
      DATA (SPROP(I,-2,22),I=1,2)/0,0/
      DATA (IFOREST(I,-3,22),I=1,2)/-2,3/
C     Diagram 23
      DATA MAPCONFIG(23)/23/
      DATA (IFOREST(I,-1,23),I=1,2)/5,4/
      DATA (SPROP(I,-1,23),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,23)/0/
      DATA (IFOREST(I,-2,23),I=1,2)/1,-1/
      DATA TPRID(-2,23)/2000005/
      DATA (SPROP(I,-2,23),I=1,2)/0,0/
      DATA (IFOREST(I,-3,23),I=1,2)/-2,3/
C     Diagram 24
      DATA MAPCONFIG(24)/24/
      DATA (IFOREST(I,-1,24),I=1,2)/5,4/
      DATA (SPROP(I,-1,24),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,24)/0/
      DATA (IFOREST(I,-2,24),I=1,2)/1,-1/
      DATA TPRID(-2,24)/2000005/
      DATA (SPROP(I,-2,24),I=1,2)/0,0/
      DATA (IFOREST(I,-3,24),I=1,2)/-2,3/
C     Diagram 25
      DATA MAPCONFIG(25)/25/
      DATA (IFOREST(I,-1,25),I=1,2)/5,3/
      DATA (SPROP(I,-1,25),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,25)/0/
      DATA (IFOREST(I,-2,25),I=1,2)/1,-1/
      DATA TPRID(-2,25)/1000005/
      DATA (SPROP(I,-2,25),I=1,2)/0,0/
      DATA (IFOREST(I,-3,25),I=1,2)/-2,4/
C     Diagram 26
      DATA MAPCONFIG(26)/26/
      DATA (IFOREST(I,-1,26),I=1,2)/5,3/
      DATA (SPROP(I,-1,26),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,26)/0/
      DATA (IFOREST(I,-2,26),I=1,2)/1,-1/
      DATA TPRID(-2,26)/1000005/
      DATA (SPROP(I,-2,26),I=1,2)/0,0/
      DATA (IFOREST(I,-3,26),I=1,2)/-2,4/
C     Diagram 27
      DATA MAPCONFIG(27)/27/
      DATA (IFOREST(I,-1,27),I=1,2)/5,3/
      DATA (SPROP(I,-1,27),I=1,2)/1000005,-1000005/
      DATA TPRID(-1,27)/0/
      DATA (IFOREST(I,-2,27),I=1,2)/1,-1/
      DATA TPRID(-2,27)/2000005/
      DATA (SPROP(I,-2,27),I=1,2)/0,0/
      DATA (IFOREST(I,-3,27),I=1,2)/-2,4/
C     Diagram 28
      DATA MAPCONFIG(28)/28/
      DATA (IFOREST(I,-1,28),I=1,2)/5,3/
      DATA (SPROP(I,-1,28),I=1,2)/2000005,-2000005/
      DATA TPRID(-1,28)/0/
      DATA (IFOREST(I,-2,28),I=1,2)/1,-1/
      DATA TPRID(-2,28)/2000005/
      DATA (SPROP(I,-2,28),I=1,2)/0,0/
      DATA (IFOREST(I,-3,28),I=1,2)/-2,4/
C     Diagram 29
      DATA MAPCONFIG(29)/29/
      DATA (IFOREST(I,-1,29),I=1,2)/4,3/
      DATA (SPROP(I,-1,29),I=1,2)/21,21/
      DATA TPRID(-1,29)/0/
      DATA (IFOREST(I,-2,29),I=1,2)/1,-1/
      DATA TPRID(-2,29)/21/
      DATA (SPROP(I,-2,29),I=1,2)/0,0/
      DATA (IFOREST(I,-3,29),I=1,2)/-2,5/
C     Number of configs
      DATA MAPCONFIG(0)/29/
