ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of MSSM_SLHA2'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_33 = ', GC_33
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_73 = ', GC_73
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_96 = ', GC_96
      WRITE(*,2) 'GC_108 = ', GC_108
      WRITE(*,2) 'GC_513 = ', GC_513
      WRITE(*,2) 'GC_518 = ', GC_518
      WRITE(*,2) 'GC_528 = ', GC_528
      WRITE(*,2) 'GC_533 = ', GC_533
